config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories, only: %i[index new create] do
    resources :transaction_items, only: %i[index new create]
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, :all, user_id: user.id
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id', inverse_of: :categories
  has_many :transaction_items, class_name: 'TransactionItem', foreign_key: 'category_id', inverse_of: :category,
                               dependent: :destroy
  has_one_attached :icon, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
  validate :icon_format

  def category_total_amount
    total_amount = 0
    transaction_items.each do |ct|
      total_amount += ct.amount
    end
    Float(total_amount).round(2)
  end

  private

  def icon_format
    return unless icon.attached?
    return if icon.blob.content_type.start_with? 'image/'

    errors.add(:icon, 'needs to be an image.')
  end
end

app/models/transaction_item.rb
class TransactionItem < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id', inverse_of: :transaction_items
  belongs_to :category, class_name: 'Category', foreign_key: 'category_id', inverse_of: :transaction_items

  validates :name, presence: true
  validates :amount, presence: true, numericality: true, comparison: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :categories, class_name: 'Category', foreign_key: 'user_id', inverse_of: :user, dependent: :destroy
  has_many :transaction_items, class_name: 'TransactionItem', foreign_key: 'user_id', inverse_of: :user,
                               dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  private

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end

  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @current_user = current_user
    @categories = @current_user.categories.order(name: :asc)
  end

  def new
    @current_user = current_user
  end

  def create
    @current_user = current_user
    category = @current_user.categories.new(category_params)
    if category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to categories_url
    else
      flash[:alert] = category.errors.full_messages.to_sentence
      render :new, status: 422
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/transaction_items_controller.rb
class TransactionItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @current_user = current_user
    @category = Category.find(params[:category_id])
    unless @current_user.categories.include? @category
      flash[:alert] = "You are not allowed to manage the #{@category.name} category. Select a category from the list."
      redirect_to categories_url
    end
    @t_order = params[:order] || 'desc'
    @transactions = @category.transaction_items.order("created_at #{@t_order}")
  end

  def new
    @current_user = current_user
    @category = Category.find(params[:category_id])
    return if @current_user.categories.include? @category

    flash[:alert] = "You are not allowed to manage the #{@category.name} category. Select a category from the list."
    redirect_to categories_url
  end

  def create
    @current_user = current_user
    category = Category.find(params[:transaction_item][:category_id])
    if @current_user.categories.include? category
      transaction = @current_user.transaction_items.new(transaction_params)
      if transaction.save
        flash[:notice] = 'Transaction was successfully created.'
        redirect_to category_transaction_items_path(params[:transaction_item][:category_id])
      else
        flash[:alert] = transaction.errors.full_messages.to_sentence
        redirect_to new_category_transaction_item_path(params[:transaction_item][:category_id])
      end
    else
      flash[:alert] = "You are not allowed to manage the #{category.name} category. Select a category from the list."
      redirect_to categories_url
    end
  end

  private

  def transaction_params
    params.require(:transaction_item).permit(:name, :amount, :category_id)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def after_inactive_sign_up_path_for(_resource)
    new_user_registration_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/transaction_items_helper.rb
module TransactionItemsHelper
end

app/views/categories/_category_card.html.erb
<li class="list__item" id="category-#{category.id}">
  <div class="item__icon">
    <%= image_tag url_for(category.icon), alt: "#{category.name}'s icon", id: "img-#{category.icon.filename}" if category.icon.attached? %>
  </div>
  <div class="item__name">
    <%= tag.p category.name %>
  </div>
  <div class="item__amount">
    <%= tag.p "$ #{category.category_total_amount}" %>
  </div>
  <%= link_to '', category_transaction_items_path(category.id), class: 'link link__card-hidden', id: "link-to-category-#{category.id}-transactions" %>
</li>

app/views/categories/index.html.erb
<%= render partial: 'layouts/header', locals: { h_title: 'CATEGORIES', h_back: false, h_submit: false } %>
<div class="box__main">
  <%= render partial: 'layouts/message' %>
  <% if @categories.count > 0 %>
    <ul class="list">
    <%= render partial: 'category_card', collection: @categories, as: :category %>
    </ul>
  <% else %>
    <%= tag.p 'There are no registered categories yet.' %>
  <% end %>
</div>
<div class="box__crud">
  <div class="link__btn-box">
    <%= link_to 'NEW CATEGORY', new_category_path, class: 'link' %>
  </div>
</div>

app/views/categories/new.html.erb
<%= render partial: 'layouts/header', locals: { h_title: 'CATEGORY', h_back: categories_path, h_submit: true } %>
<div class="box__main box__main-full">
  <%= render partial: 'layouts/message' %>
  <%= form_with model: Category.new, class: 'new_user' do |f| %>
    <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
    </div>
    <div class="field">
    <%= f.label :icon %><br />
    <%= f.file_field :icon %>
    </div>
    <%= f.submit 'Save', class: 'btn-header' %>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="splash__screen">
  <div class="splash__name">
    <%= tag.h1 'Snapcheck', class: 'title__splash' %>
    </div>
    <div class="splash__menu">
    <div class="link__btn-box link__btn-blue">
    <%= link_to 'LOG IN', new_user_session_path, class: 'link link__btn' %>
    </div>
    <div class="link__btn-box link__btn-white">
    <%= link_to 'SIGN UP', new_user_registration_path, class: 'link link__btn' %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="box__nav">
  <div class="nav__back">
    <% if h_back %>
      <%= link_to h_back, class: 'link' do %>
        <i class="fa-solid fa-arrow-left-long"></i>
      <% end %>
    <% else %>
      <%= link_to 'Log Out', destroy_user_session_path, 'data-turbo-method': :delete, class: 'link' %>
    <% end %>
  </div>
  <div class="nav__title">
  <%= tag.h1 h_title, class: 'title__header' %>
  </div>
  <div class="nav__submit">
  </div>
</nav>

app/views/layouts/_message.html.erb
<div class="box__message">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag '/favicon.ico' %>
    <meta name="description" content="A mobile web application where users can manage their budget. Users can have a list of transactions associated with a category, so that they can see how much money they spent and on what.">
    <meta name="keywords" content="transactions, budget">
    <meta property="og:title" content="Budget app">
    <meta property="og:description" content="A mobile web application where users can manage their budget. Users can have a list of transactions associated with a category, so that they can see how much money they spent and on what.">
    <meta property="og:type" content="website">
    <meta property="og:url" content="http://ec2-13-56-254-159.us-west-1.compute.amazonaws.com/">
    <meta property="og:image" content="ba-screenshot-1200x627.png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/48cdc727d4.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/transaction_items/_transaction_card.html.erb
<li class="list__item" id="transaction-#{transaction.id}">
  <div class="item__desc">
    <%= tag.p transaction.name %>
    <%= tag.span transaction.created_at.strftime('%m %b %Y %I:%M%p').gsub('AM','am').gsub('PM','pm').gsub(':00',''), class: 'transaction-date text__small' %>
  </div>
  <div class="item__amount">
    <%= tag.p "$ #{transaction.amount}" %>
  </div>
</li>

app/views/transaction_items/index.html.erb
<%= render partial: 'layouts/header', locals: { h_title: 'TRANSACTIONS', h_back: categories_path, h_submit: false } %>
<% if @transactions.count > 0 %>
  <div class="box__filter">
  <%= link_to category_transaction_items_path(@category.id, order: (@t_order == 'asc' ? 'desc' : 'asc')), class: 'link' do %>
    <% if @t_order == 'desc' %>
      <i class="fa-solid fa-arrow-down-1-9"></i>
      Most ancient
    <% else %>
      <i class="fa-solid fa-arrow-down-9-1"></i>
      Most recent
    <% end %>
  <% end %>
  </div>
<% end %>
<div class="box__main">
  <%= render partial: 'layouts/message' %>
  <% if @transactions.count > 0 %>
    <ul class="list">
    <%= render partial: 'transaction_card', collection: @transactions, as: :transaction %>
    </ul>
  <% else %>
    <%= tag.p 'There are no transactions recorded for this category yet.' %>
  <% end %>
</div>
<div class="box__crud">
  <div class="link__btn-box">
  <%= link_to 'NEW TRANSACTION', new_category_transaction_item_path(@category.id), class: 'link' %>
  </div>
</div>

app/views/transaction_items/new.html.erb
<%= render partial: 'layouts/header', locals: { h_title: 'TRANSACTION', h_back: category_transaction_items_path(@category.id), h_submit: true } %>
<div class="box__main box__main-full">
  <%= render partial: 'layouts/message' %>
  <%= form_with model: TransactionItem.new, url: category_transaction_items_path do |f| %>
    <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
    </div>
    <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
    </div>
    <%= f.hidden_field :category_id, value: @category.id %>
    <%= f.submit 'Save', class: 'btn-header' %>
  <% end %>
</div>